os: linux
dist: bionic
language: shell

.opam: &OPAM
  language: shell
  services: docker
  install: |
    # Prepare the COQ container
    docker pull ${COQ_IMAGE}
    docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${PACKAGE} -w /home/coq/${PACKAGE} ${COQ_IMAGE}
    docker exec COQ /bin/bash --login -c "
      # This bash script is double-quoted to interpolate Travis CI env vars:
      echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex  # -e = exit on failure; -x = trace for debug
      opam update -y
      opam pin add coq-hammer-tactics . -y -n -k path
      opam pin add coq-hammer . -y -n -k path
      opam install ${PACKAGE} -y -j ${NJOBS} --deps-only
      opam config list
      opam repo list
      opam list
      "
  script:
  - echo -e "${ANSI_YELLOW}Building ${PACKAGE}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex
      sudo chown -R coq:coq /home/coq/${PACKAGE}
      opam install ${PACKAGE} -v -y -t -j ${NJOBS}
      "
  - docker stop COQ  # optional
  - echo -en 'travis_fold:end:script\\r'

.nix: &NIX
  language: nix
  install:
  # for cachix we need travis to be a trusted nix user
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  script:
  - nix-build --argstr coq-version-or-url "$COQ" --extra-substituters https://coq.cachix.org --trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= coq.cachix.org-1:5QW/wwEnD+l2jvN6QRbRRsa4hBHG3QiQQ26cxu1F5tI="

jobs:
  include:

  # Test supported versions of Coq via Nix
  - env:
    - COQ=8.11
    <<: *NIX

  # Test supported versions of Coq via OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.11
    - PACKAGE=coq-hammer.8.11.dev
    - NJOBS=2
    <<: *OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.11
    - PACKAGE=coq-hammer-tactics.8.11.dev
    - NJOBS=2
    <<: *OPAM
