From Hammer Require Import Tactics.
Require List Arith ZArith Bool.

Hint Rewrite -> Arith.PeanoNat.Nat.add_0_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.add_1_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.sub_0_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_0_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_1_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.add_assoc : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_assoc : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_add_distr_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_add_distr_l : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_sub_distr_r : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_sub_distr_l : shints.
Hint Rewrite -> Arith.PeanoNat.Nat.sub_add_distr : shints.
Hint Rewrite <- Arith.PeanoNat.Nat.leb_antisym : shints.
Hint Rewrite <- Arith.PeanoNat.Nat.ltb_antisym : shints.
Hint Rewrite -> ZArith.BinInt.Z.add_0_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.add_1_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.sub_0_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_0_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_1_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.add_assoc : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_assoc : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_add_distr_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_add_distr_l : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_sub_distr_r : shints.
Hint Rewrite -> ZArith.BinInt.Z.mul_sub_distr_l : shints.
Hint Rewrite -> ZArith.BinInt.Z.sub_add_distr : shints.
Hint Rewrite -> List.in_app_iff : shints.
Hint Rewrite -> List.in_map_iff : shints.
Hint Rewrite -> List.in_inv : shints.
Hint Rewrite <- List.app_assoc : shints.
Hint Rewrite -> Bool.orb_true_r : shints.
Hint Rewrite -> Bool.orb_false_r : shints.
Hint Rewrite -> Bool.andb_true_r : shints.
Hint Rewrite -> Bool.andb_false_r : shints.

Hint Rewrite -> Bool.orb_true_r : sbool.
Hint Rewrite -> Bool.orb_true_l : sbool.
Hint Rewrite -> Bool.orb_false_r : sbool.
Hint Rewrite -> Bool.orb_false_l : sbool.
Hint Rewrite -> Bool.andb_true_r : sbool.
Hint Rewrite -> Bool.andb_true_l : sbool.
Hint Rewrite -> Bool.andb_false_r : sbool.
Hint Rewrite -> Bool.andb_false_l : sbool.

Hint Rewrite -> List.app_nil_r : slist.
Hint Rewrite -> List.rev_length : slist.
Hint Rewrite -> List.app_length : slist.
Hint Rewrite -> List.seq_length : slist.
Hint Rewrite -> List.map_length : slist.
Hint Rewrite -> List.map_length : slist.
Hint Rewrite -> List.map_nth : slist.
Hint Rewrite -> List.rev_unit : slist.
Hint Rewrite -> List.rev_involutive : slist.
Hint Rewrite -> List.in_app_iff : slist.
Hint Rewrite -> List.in_map_iff : slist.
Hint Rewrite -> List.in_inv : slist.
Hint Rewrite <- List.app_assoc : slist.

Hint Rewrite -> Arith.PeanoNat.Nat.add_0_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.add_1_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.sub_0_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_0_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_1_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.add_assoc : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_assoc : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_add_distr_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_add_distr_l : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_sub_distr_r : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.mul_sub_distr_l : sarith.
Hint Rewrite -> Arith.PeanoNat.Nat.sub_add_distr : sarith.
Hint Rewrite <- Arith.PeanoNat.Nat.leb_antisym : sarith.
Hint Rewrite <- Arith.PeanoNat.Nat.ltb_antisym : sarith.

Hint Rewrite -> ZArith.BinInt.Z.add_0_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.add_1_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.sub_0_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_0_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_1_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.add_assoc : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_assoc : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_add_distr_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_add_distr_l : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_sub_distr_r : szarith.
Hint Rewrite -> ZArith.BinInt.Z.mul_sub_distr_l : szarith.
Hint Rewrite -> ZArith.BinInt.Z.sub_add_distr : szarith.
