(rule
 (alias runtest)
 (deps
  (source_tree .)
  ../../Makefile
  ../../_CoqProject.tactics
  ../../_CoqProject.plugin)
 (action
  (run bash -c "set -euo pipefail
repo=$(git rev-parse --show-toplevel)
cd \"$repo\"
rm -rf _check-install
make prepare-local-install
make install \\
  COQLIBINSTALL=\"$repo/_check-install/coq/user-contrib\" \\
  COQPLUGININSTALL=\"$repo/_check-install\" \\
  BINDIR=\"$repo/_check-install/bin/\" \\
  COQFLAGS=\"-coqlib $repo/_check-install/coq\"
make -B -C tests/plugin all \\
  LOCAL_ROCQLIB=\"$repo/_check-install/coq\" \\
  COQC=\"rocq c -coqlib $repo/_check-install/coq\"")))

(alias
 (name extraction)
 (deps (alias runtest)))
